activemq:
    restart: always
    image: activemq
    ports:
     - 8161:8161
     - 61616:61616
    environment:
     - ACTIVEMQ_VERSION=5.14.4

webapp:
    restart: always
    image: webapp
    ports:
     - 8081:8080
    environment:
     - WEBAPP_VERSION=1.0

